# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 08:56
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilloResponseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_phone_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='From Number')),
                ('to_phone_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='To Number')),
                ('message_sid', models.CharField(blank=True, max_length=120, null=True, verbose_name='Message SID from Twillo')),
                ('date_send', models.DateTimeField(blank=True, null=True, verbose_name='Message Created Date')),
            ],
        ),
        migrations.CreateModel(
            name='UserDataTable',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('phone_no', models.CharField(blank=True, max_length=120, null=True, verbose_name='User Phone Number')),
                ('active_date', models.DateTimeField(auto_now_add=True, verbose_name='Activeted Date')),
                ('trial_period', models.BooleanField(default=True, verbose_name='Trial period ?')),
                ('user_type', models.CharField(choices=[('ADM', 'Admin'), ('USR', 'Portal User')], default='USR', max_length=3)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
