# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userconfirmationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmationcode',
            name='date_created',
            field=models.DateTimeField(verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='userdatatable',
            name='active_date',
            field=models.DateTimeField(verbose_name='Activeted Date'),
        ),
    ]
