# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userconfirmationcode_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmationcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserDataTable'),
        ),
        migrations.AlterField(
            model_name='userdatatable',
            name='phone_no',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='User Phone Number'),
        ),
    ]
