# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170412_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfirmationcode',
            name='message_sid',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Message SID from Twillo'),
        ),
    ]
