# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 14:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userconfirmationcode_message_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twilloresponsedata',
            name='date_send',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 12, 14, 22, 7, 760922, tzinfo=utc), null=True, verbose_name='Message Created Date'),
        ),
    ]
