# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170412_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twilloresponsedata',
            name='date_send',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Message Created Date'),
        ),
    ]
